#!/bin/bash

echo
echo "Removing the files and directories generated by Maven..."
echo
mvn clean

echo
echo "Removing dynamic library..."
echo
rm -rf src/main/native/libpore.so

rm -rf ./hpg-pore-0.1.0-jar-with-dependencies.jar .
rm -rf libhpgpore.so .
