/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencb_hadoop_pore_NativePoreSupport */

#ifndef _Included_org_opencb_hpg_pore_NativePoreSupport
#define _Included_org_opencb_hpg_pore_NativePoreSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencb_hadoop_pore_NativePoreSupport
 * Method:    getFastqs
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencb_hpg_1pore_NativePoreSupport_getFastqs
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_opencb_hadoop_pore_NativePoreSupport
 * Method:    getInfo
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencb_hpg_1pore_NativePoreSupport_getInfo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_opencb_hadoop_pore_NativePoreSupport
 * Method:    getEvents
 * Signature: ([BLjava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencb_hpg_1pore_NativePoreSupport_getEvents
  (JNIEnv *, jobject, jbyteArray, jstring, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
